const books = [
  {
    "title": "The Catcher in the Rye",
    "subtitle": "",
    "author": "J. D. Sallinger",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "USA",
    "ISBN": "9780241984758",
    "Designer": "",
    "year": "1951",
    "pages": "240",
    "width[mm]": "138.00",
    "height[mm]": "204.00",
  },
  {
    "title": "To Kill A Mockingbird",
    "subtitle": "",
    "author": "Harper Lee",
    "publisher": "J.B.Lippincot & Co.",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "USA",
    "ISBN": "9780099549482",
    "Designer": "",
    "year": "1960",
    "pages": "320",
    "width[mm]": "177.00",
    "height[mm]": "110.00"
  },
  {
    "title": "Livro Sexto",
    "subtitle": "",
    "author": "Sophia de Mello Breyner Andresen",
    "publisher": "Caminho",
    "collection": "Obras de Sophia de Mello Breyner Andresen",
    "genre": "Poetry",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789723717839",
    "Designer": "",
    "year": "1962",
    "pages": "112",
    "width[mm]": "205.00",
    "height[mm]": "147.00"
  },
  {
    "title": "Molloy",
    "subtitle": "",
    "author": "Samuel Buckett",
    "publisher": "Les Editions de Minute",
    "collection": "The Beckett Trilogy",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "9789727087174",
    "Designer": "",
    "year": "1951",
    "pages": "220",
    "width[mm]": "211.00",
    "height[mm]": "138.00"
  },
  {
    "title": "The Ragazzi",
    "subtitle": "",
    "author": "Pier Paolo Passolini",
    "publisher": "Wagenbach Klaus",
    "collection": "",
    "genre": "Novel",
    "language": "Italian",
    "country": "Italy",
    "ISBN": "9781857549720",
    "Designer": "",
    "year": "1955",
    "pages": "256",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Ultramarina",
    "subtitle": "",
    "author": "Malcolm Lowry",
    "publisher": "Jonathan Cape Ltd",
    "collection": "Dois Mundos",
    "genre": "Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9789723810400",
    "Designer": "",
    "year": "1933",
    "pages": "262",
    "width[mm]": "210.00",
    "height[mm]": "145.00"
  },
  {
    "title": "For Whom The Bell Tolls",
    "subtitle": "",
    "author": "Ernest Hemingway",
    "publisher": "Charles Scribner's Sons",
    "collection": "Presenting Series",
    "genre": "Novel",
    "language": "English",
    "country": "USA",
    "ISBN": "9781909621428",
    "Designer": "",
    "year": "1940",
    "pages": "624",
    "width[mm]": "157.00",
    "height[mm]": "102.00"
  },
  {
    "title": "Jacques le fataliste et son maitrê",
    "subtitle": "",
    "author": "Denis Diderot",
    "publisher": "Buisson",
    "collection": "",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "9782070338955",
    "Designer": "",
    "year": "1796",
    "pages": "384",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Nostromo",
    "subtitle": "",
    "author": "Joseph Conrad",
    "publisher": "",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "UK",
    "ISBN": "9789722037389",
    "Designer": "",
    "year": "1904",
    "pages": "528",
    "width[mm]": "227.00",
    "height[mm]": "144.00"
  },
  {
    "title": "Travels into several remote nations of the World",
    "subtitle": "",
    "author": "Jonathan Swift",
    "publisher": "Benjamin Motte",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "Ireland",
    "ISBN": "9781175070920",
    "Designer": "",
    "year": "1726",
    "pages": "254",
    "width[mm]": "969.00",
    "height[mm]": "744.00"
  },
  {
    "title": "Ilíada",
    "subtitle": "",
    "author": "Homero",
    "publisher": "",
    "collection": "",
    "genre": "Epic Poetry",
    "language": "Homeric Greek",
    "country": "Greece",
    "ISBN": "",
    "Designer": "",
    "year": "8th century bC",
    "pages": "",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Clepsidra",
    "subtitle": "",
    "author": "Camilo Pessanha",
    "publisher": "Edições Ática",
    "collection": "Colecção Poesia",
    "genre": "Poetry",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "",
    "Designer": "",
    "year": "1956",
    "pages": "551",
    "width[mm]": "200.00",
    "height[mm]": "150.00"
  },
  {
    "title": "Crónica de D.João I",
    "subtitle": "",
    "author": "Fernão Lopes",
    "publisher": "Livraria Civilização",
    "collection": "Série Régia da Biblioteca Histórica",
    "genre": "Historiography",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "",
    "Designer": "",
    "year": "1945",
    "pages": "455",
    "width[mm]": "145.00",
    "height[mm]": "215.00"
  },
  {
    "title": "El ingenioso hidalgo Don Quixote de La Mancha",
    "subtitle": "",
    "author": "Miguel de Cervantes",
    "publisher": "Francisco de Robles",
    "collection": "",
    "genre": "Novel, Adventure, Chivalric Romance",
    "language": "Early Modern Spanish",
    "country": "Spain",
    "ISBN": "",
    "Designer": "Francisco de Robles (printer)",
    "year": "1605",
    "pages": "",
    "width[mm]": "185.00",
    "height[mm]": "127.00"
  },
  {
    "title": "Germinal",
    "subtitle": "",
    "author": "Émile Zola",
    "publisher": "G. Charpentier",
    "collection": "Les Rougon-Macquart",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "",
    "Designer": "",
    "year": "1885",
    "pages": "591",
    "width[mm]": "115.00",
    "height[mm]": "185.00"
  },
  {
    "title": "Medeia",
    "subtitle": "",
    "author": "Eurípides",
    "publisher": "",
    "collection": "",
    "genre": "Greek Tragedy, Play",
    "language": "Ancient Greek",
    "country": "Greece",
    "ISBN": "",
    "Designer": "",
    "year": "431 b.C",
    "pages": "",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "O Tango de Satanás ",
    "subtitle": "",
    "author": "László Krasznahorkai",
    "publisher": "Antígona, 2018",
    "collection": "",
    "genre": "Novel",
    "language": "Hungarian",
    "country": "Hungary",
    "ISBN": "9789726083252",
    "Designer": "Miguel Carneiro",
    "year": "1985",
    "pages": "280",
    "width[mm]": "134.00",
    "height[mm]": "208.00"
  },
  {
    "title": "Poemas de Deus e do Diabo",
    "subtitle": "",
    "author": "José Régio",
    "publisher": "Quasi Edições, 2006",
    "collection": "",
    "genre": "Poetry",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789728632717",
    "Designer": "",
    "year": "1925",
    "pages": "152",
    "width[mm]": "144.00",
    "height[mm]": "193.00"
  },
  {
    "title": "Sinais de Fogo",
    "subtitle": "",
    "author": "Jorge de Sena ",
    "publisher": "Edições Asa, 2001",
    "collection": "Finisterra",
    "genre": "Fiction",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789724116778",
    "Designer": "",
    "year": "1979",
    "pages": "540",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "The Life and Opinions of Tristam Shandy, Gentleman",
    "subtitle": "",
    "author": "Laurence Sterne",
    "publisher": "Penguin Books, 2003",
    "collection": "Penguin Classics",
    "genre": "Novel",
    "language": "English",
    "country": "Great Britain",
    "ISBN": "9780141439778",
    "Designer": "",
    "year": "1759 – 1767",
    "pages": "735",
    "width[mm]": "127.00",
    "height[mm]": "280.00"
  },
  {
    "title": "A Study in Scarlet",
    "subtitle": "",
    "author": "A. Conan Doyle",
    "publisher": "Ward Lock & Co",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9781495384622",
    "Designer": "",
    "year": "1887",
    "pages": "84",
    "width[mm]": "152.00",
    "height[mm]": "229.00"
  },
  {
    "title": "A Sudden Liberating Thought",
    "subtitle": "",
    "author": "Kjell Askildsen",
    "publisher": "Norvik Press",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "UK",
    "ISBN": "9781870041249",
    "Designer": "",
    "year": "1994",
    "pages": "240",
    "width[mm]": "140.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Buddenbrooks",
    "subtitle": "",
    "author": "Thomas Mann",
    "publisher": "S. Fischer Verlag",
    "collection": "",
    "genre": "Novel, Fiction, Family Saga",
    "language": "English",
    "country": "Germany",
    "ISBN": "9789722044998",
    "Designer": "",
    "year": "1901",
    "pages": "732",
    "width[mm]": "135.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Selected Stories",
    "subtitle": "",
    "author": "Anton Chekhov",
    "publisher": "Wordsworth Editions",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "UK",
    "ISBN": "9781853262883",
    "Designer": "",
    "year": "1903",
    "pages": "208",
    "width[mm]": "129.00",
    "height[mm]": "198.00"
  },
  {
    "title": "La Monnaie Vivante",
    "subtitle": "",
    "author": "Pierre Klossowski",
    "publisher": "Payot & Rivages",
    "collection": "Rivages Poche",
    "genre": "Philosophy",
    "language": "French",
    "country": "France",
    "ISBN": "9782743602734",
    "Designer": "",
    "year": "1970",
    "pages": "96",
    "width[mm]": "109.00",
    "height[mm]": "169.00"
  },
  {
    "title": "A Casa Grande de Romarigães",
    "subtitle": "",
    "author": "Aquilino Ribeiro",
    "publisher": "Livraria Bertrand",
    "collection": "",
    "genre": "Novel",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789722516297",
    "Designer": "",
    "year": "1957",
    "pages": "352",
    "width[mm]": "152.00",
    "height[mm]": "231.00"
  },
  {
    "title": "A Vida Sem Princípios",
    "subtitle": "",
    "author": "Henry David Thoreau",
    "publisher": "Antígona",
    "collection": "",
    "genre": "Philosophy",
    "language": "Portuguese",
    "country": "USA",
    "ISBN": "9789726082736",
    "Designer": "",
    "year": "1863",
    "pages": "80",
    "width[mm]": "128.00",
    "height[mm]": "208.00"
  },
  {
    "title": "Middlemarch",
    "subtitle": "A Study of Provincial Life",
    "author": "George Eliot",
    "publisher": "William Blackwood and Sons",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9781496017727",
    "Designer": "",
    "year": "1874",
    "pages": "548",
    "width[mm]": "152.00",
    "height[mm]": "229.00"
  },
  {
    "title": "Le Droit À La Paresse",
    "subtitle": "",
    "author": "Paul Lafargue",
    "publisher": "La Decouverte",
    "collection": "",
    "genre": "Essay",
    "language": "French",
    "country": "France",
    "ISBN": "9782707159496",
    "Designer": "",
    "year": "1883",
    "pages": "96",
    "width[mm]": "125.00",
    "height[mm]": "190.00"
  },
  {
    "title": "The Stranger",
    "subtitle": "",
    "author": "Albert Camus",
    "publisher": "Perfection Learning",
    "collection": "",
    "genre": "Novel, Philosophy, Fiction, Crime, Absurdism",
    "language": "English",
    "country": "France",
    "ISBN": "9780812416695",
    "Designer": "",
    "year": "1989",
    "pages": "120",
    "width[mm]": "125.00",
    "height[mm]": "207.00"
  },
  {
    "title": "Le Rouge et Le Noir",
    "subtitle": "",
    "author": "Stendhal",
    "publisher": "Levavasseur",
    "collection": "",
    "genre": "Psychological Romance",
    "language": "French",
    "country": "France",
    "ISBN": "",
    "Designer": "",
    "year": "1830",
    "pages": "576",
    "width[mm]": "110.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Os Irmãos Karamazov",
    "subtitle": "",
    "author": "Fyodor Dostoyevski",
    "publisher": "The Russian Messenger",
    "collection": "",
    "genre": "Novel",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9722329723",
    "Designer": "",
    "year": "1879",
    "pages": "811",
    "width[mm]": "152.00",
    "height[mm]": "231.00"
  },
  {
    "title": "To the Lighthouse",
    "subtitle": "",
    "author": "Virginia Woolf",
    "publisher": "Hogarth Press",
    "collection": "",
    "genre": "Modernist Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9780141183411",
    "Designer": "",
    "year": "1927",
    "pages": "320",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Orlando",
    "subtitle": "A Biography",
    "author": "Virginia Woolf",
    "publisher": "Hogarth Press",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9727082459",
    "Designer": "",
    "year": "1928",
    "pages": "134",
    "width[mm]": "152.00",
    "height[mm]": "231.00"
  },
  {
    "title": "Absalom, Absalom!",
    "subtitle": "",
    "author": "William Faulkner",
    "publisher": "Random House",
    "collection": "",
    "genre": "Southern Gothic",
    "language": "English",
    "country": "USA",
    "ISBN": "679732187",
    "Designer": "",
    "year": "1936",
    "pages": "384",
    "width[mm]": "126.00",
    "height[mm]": "196.00"
  },
  {
    "title": "Golpes",
    "subtitle": "",
    "author": "Jean Meckert",
    "publisher": "Gallimard",
    "collection": "",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "9789726082606",
    "Designer": "",
    "year": "1942",
    "pages": "272",
    "width[mm]": "129.00",
    "height[mm]": "208.00"
  },
  {
    "title": "A Sibila",
    "subtitle": "",
    "author": "Agustina Bessa-Luís",
    "publisher": "Guimarães",
    "collection": "",
    "genre": "Fiction",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789726655671",
    "Designer": "",
    "year": "1954",
    "pages": "296",
    "width[mm]": "139.00",
    "height[mm]": "219.00"
  },
  {
    "title": "Night Song",
    "subtitle": "",
    "author": "John A. Williams",
    "publisher": "Farrar, Straus & Giroux",
    "collection": "",
    "genre": "Psychological Romance",
    "language": "English",
    "country": "USA",
    "ISBN": "9780911860511",
    "Designer": "",
    "year": "1955",
    "pages": "219",
    "width[mm]": "124.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Aparição",
    "subtitle": "",
    "author": "Vergílio Ferreira",
    "publisher": "Portugália ",
    "collection": "",
    "genre": "Fiction",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789897221453",
    "Designer": "",
    "year": "1959",
    "pages": "248",
    "width[mm]": "149.00",
    "height[mm]": "230.00"
  },
  {
    "title": "El Amor en los Tiempos del Cólera",
    "subtitle": "",
    "author": "Gabriel García Marquez",
    "publisher": "Oveja Negra",
    "collection": "",
    "genre": "Fantastic Realism",
    "language": "Castilian",
    "country": "Colombia",
    "ISBN": "9788497592451",
    "Designer": "",
    "year": "1985",
    "pages": "496",
    "width[mm]": "125.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Hamlet",
    "subtitle": "The Tragedie of Hamlet, Prince of Denmark",
    "author": " William Shakespeare",
    "publisher": "I.R. for N.L.",
    "collection": "",
    "genre": "Tragedy, Drama",
    "language": "English",
    "country": "England",
    "ISBN": "",
    "Designer": "",
    "year": "1599",
    "pages": "",
    "width[mm]": "150.00",
    "height[mm]": "230.00"
  },
  {
    "title": "Sons and Lovers",
    "subtitle": "",
    "author": "D.H. Lawrence ",
    "publisher": "Gerald Duckworth and Company Ltd ",
    "collection": "",
    "genre": "Romance",
    "language": "English",
    "country": "England",
    "ISBN": "9780141197722",
    "Designer": "",
    "year": "1913",
    "pages": "423",
    "width[mm]": "139.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Gargantua et Pantagruel",
    "subtitle": "",
    "author": "François Rabelais",
    "publisher": "François Rabelais",
    "collection": "",
    "genre": "Satire",
    "language": "French",
    "country": "France",
    "ISBN": "",
    "Designer": "Gustave et Duré",
    "year": "1532",
    "pages": "",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Mau Tempo no Canal",
    "subtitle": "",
    "author": "Vitorino Nemésio",
    "publisher": "Bertrand",
    "collection": "",
    "genre": "Romance",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789896600419",
    "Designer": "",
    "year": "1944",
    "pages": "478",
    "width[mm]": "125.00",
    "height[mm]": "189.00"
  },
  {
    "title": "Guerra e Paz",
    "subtitle": "",
    "author": "Liev Tolstói",
    "publisher": "Russkii Vestnik",
    "collection": "",
    "genre": "Historical,Romance",
    "language": "Russian",
    "country": "Russía",
    "ISBN": "",
    "Designer": "",
    "year": "1864-1869",
    "pages": "1225",
    "width[mm]": "150.00",
    "height[mm]": "220.00"
  },
  {
    "title": "Húmus",
    "subtitle": "",
    "author": "Raul Brandão",
    "publisher": "Renascença Portuguesa",
    "collection": "",
    "genre": "Romance, Fiction",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789729916304",
    "Designer": "",
    "year": "1917",
    "pages": "240",
    "width[mm]": "120.00",
    "height[mm]": "200.00"
  },
  {
    "title": "The Tale of Genji",
    "subtitle": "",
    "author": "Murasaki Shikibu",
    "publisher": "Murasaki Shikibu",
    "collection": "",
    "genre": "Romance, Fiction",
    "language": "Japanese",
    "country": "Japan",
    "ISBN": "",
    "Designer": "",
    "year": "1021",
    "pages": "",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Grande Sertão: Veredas",
    "subtitle": "",
    "author": "João Guimarães Rosa",
    "publisher": "José Olympio",
    "collection": "",
    "genre": "Romance",
    "language": "Portuguese",
    "country": "Brasil",
    "ISBN": "9789896658137",
    "Designer": "Poty Lazzarotto",
    "year": "1956",
    "pages": "602",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Season of Migration to the North",
    "subtitle": "",
    "author": "Tayeb Salih ",
    "publisher": "Tayeb Salih ",
    "collection": "",
    "genre": "Novel",
    "language": "Arabic",
    "country": "Sudan",
    "ISBN": "9780435909741",
    "Designer": "",
    "year": "1966",
    "pages": "176",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Candide",
    "subtitle": "ou l'Optimisme",
    "author": "Voltaire",
    "publisher": "Dover Publication",
    "collection": "",
    "genre": "Satire",
    "language": "French",
    "country": "France",
    "ISBN": "486266893",
    "Designer": "",
    "year": "1759",
    "pages": "129",
    "width[mm]": "173.00",
    "height[mm]": "256.00"
  },
  {
    "title": "Great Expectations",
    "subtitle": "",
    "author": "Charles Dickens",
    "publisher": "Oxford University Press",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "England",
    "ISBN": "192833596",
    "Designer": "",
    "year": "1861",
    "pages": "505",
    "width[mm]": "150.00",
    "height[mm]": "230.00"
  },
  {
    "title": "Pnin",
    "subtitle": "",
    "author": "Vladimir Nabokov",
    "publisher": "Everyman's Library",
    "collection": "",
    "genre": "Novel",
    "language": "English ",
    "country": "United States of America",
    "ISBN": "1400041988",
    "Designer": "",
    "year": "1957",
    "pages": "184",
    "width[mm]": "100.00",
    "height[mm]": "170.00"
  },
  {
    "title": "Sôbolos Rios Que Vão",
    "subtitle": "",
    "author": "António Lobo Antunes",
    "publisher": "Dom Quixote",
    "collection": "",
    "genre": "Novel",
    "language": "Português",
    "country": "Portugal",
    "ISBN": "9789722041447",
    "Designer": "",
    "year": "2010",
    "pages": "199",
    "width[mm]": "148.00",
    "height[mm]": "216.00"
  },
  {
    "title": "The Tin Drum",
    "subtitle": "",
    "author": "Günter Grass",
    "publisher": "Vintage",
    "collection": "",
    "genre": "Novel",
    "language": "German",
    "country": "Germany",
    "ISBN": "99483505",
    "Designer": "",
    "year": "1959",
    "pages": "580",
    "width[mm]": "94.00",
    "height[mm]": "145.00"
  },
  {
    "title": "The 120 Days of Sodom",
    "subtitle": "Or the School of Libertinage",
    "author": "Marquis de Sade",
    "publisher": "Wilder Publications",
    "collection": "",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "1604594187",
    "Designer": "",
    "year": "1904",
    "pages": "376",
    "width[mm]": "130.00",
    "height[mm]": "216.00"
  },
  {
    "title": "One Hundred Days of Solitude",
    "subtitle": "",
    "author": "Gabriel García Marquez",
    "publisher": "Wisdom Publications",
    "collection": "",
    "genre": "Novel",
    "language": "Spanish",
    "country": "Argentina",
    "ISBN": "861715381",
    "Designer": "",
    "year": "1967",
    "pages": "144",
    "width[mm]": "130.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Sentimental Education",
    "subtitle": "",
    "author": "Gustave Flaubert",
    "publisher": "Penguin Classics",
    "collection": "",
    "genre": "Realism",
    "language": "English",
    "country": "France",
    "ISBN": "140447970",
    "Designer": "",
    "year": "1869",
    "pages": "460",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Old Goriot",
    "subtitle": "",
    "author": "Honoré de Balzac",
    "publisher": "Penguin Classics",
    "collection": "",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "039397166X",
    "Designer": "",
    "year": "1835",
    "pages": "304",
    "width[mm]": "130.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Heart of Darkness",
    "subtitle": "",
    "author": "Joseph Conrad",
    "publisher": "Green Integer",
    "collection": "",
    "genre": "Novella",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "1892295490",
    "Designer": "",
    "year": "1897",
    "pages": "188",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Arte de Ser Português",
    "subtitle": "",
    "author": "Teixeira de Pascoaes",
    "publisher": "Edições Colibri",
    "collection": "",
    "genre": "Prosa",
    "language": "Português",
    "country": "Portugal",
    "ISBN": "9789896896447",
    "Designer": "",
    "year": "1915",
    "pages": "312",
    "width[mm]": "160.00",
    "height[mm]": "230.00"
  },
  {
    "title": "Brave New World",
    "subtitle": "",
    "author": "Aldous Huxley",
    "publisher": "Vintage Publishing",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "USA",
    "ISBN": "9780099518471",
    "Designer": "",
    "year": "2007",
    "pages": "288",
    "width[mm]": "126.00",
    "height[mm]": "195.00"
  },
  {
    "title": "Confessions of Zeno",
    "subtitle": "",
    "author": "Italo Svevo",
    "publisher": "Quercus Publishing",
    "collection": "Jeeves & Wooster",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781787474178",
    "Designer": "",
    "year": "2018",
    "pages": "592",
    "width[mm]": "129.00",
    "height[mm]": "198.00"
  },
  {
    "title": "Crime and Punishment",
    "subtitle": "",
    "author": "Fyodor M Dostoevsky ",
    "publisher": "Penguin Putman INC",
    "collection": "Graduate Test Preparation",
    "genre": "Fiction",
    "language": "English",
    "country": "USA",
    "ISBN": "9780451530066",
    "Designer": "",
    "year": "2001",
    "pages": "560",
    "width[mm]": "105.00",
    "height[mm]": "170.00"
  },
  {
    "title": "Mrs. Dalloway",
    "subtitle": "",
    "author": "Virginia Woof",
    "publisher": "Alma Books LTD",
    "collection": "Alma Classics Evergreens",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781847494009",
    "Designer": "",
    "year": "2015",
    "pages": "224",
    "width[mm]": "126.00",
    "height[mm]": "196.00"
  },
  {
    "title": "Oblomov",
    "subtitle": "",
    "author": "Ivan Goncharov",
    "publisher": "Alma Books LTD",
    "collection": "Alma Classics Evergreens",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781847493446",
    "Designer": "",
    "year": "2014",
    "pages": "540",
    "width[mm]": "127.00",
    "height[mm]": "196.00"
  },
  {
    "title": "Pena Capital",
    "subtitle": "",
    "author": "Mário Cesariny de Vasconcelos",
    "publisher": "Assírio & Alvim",
    "collection": "",
    "genre": "Poesia",
    "language": "Português ",
    "country": "Portugal",
    "ISBN": "9789723705126",
    "Designer": "",
    "year": "2004",
    "pages": "240",
    "width[mm]": "144.00",
    "height[mm]": "205.00"
  },
  {
    "title": "The Postmodern Condition",
    "subtitle": "",
    "author": "Jean François Lyotard",
    "publisher": "Manchester University Press",
    "collection": "",
    "genre": "Society & Politics",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9780719014505",
    "Designer": "",
    "year": "1984",
    "pages": "144",
    "width[mm]": "154.00",
    "height[mm]": "232.00"
  },
  {
    "title": "The Time Machine",
    "subtitle": "",
    "author": "H. G. Wells",
    "publisher": "Pan Macmillan",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United Kindon",
    "ISBN": "9781509858538",
    "Designer": "",
    "year": "2017",
    "pages": "160",
    "width[mm]": "110.00",
    "height[mm]": "178.00"
  },
  {
    "title": "The Turn of the Screw",
    "subtitle": "",
    "author": "Henry James",
    "publisher": "HarperCollins Publishers",
    "collection": "Collins Classics",
    "genre": "Fiction",
    "language": "English",
    "country": "USA",
    "ISBN": "9780007420285",
    "Designer": "",
    "year": "2011",
    "pages": "192",
    "width[mm]": "110.00",
    "height[mm]": "176.00"
  },
  {
    "title": "Romancero Gitano",
    "subtitle": "",
    "author": "Federico Garcia Lorca",
    "publisher": "Editorial Moderna",
    "collection": "",
    "genre": "poetry",
    "language": "Spanish",
    "country": "Santiago de Chile",
    "ISBN": "9788437601144",
    "Designer": "",
    "year": "1926",
    "pages": "97",
    "width[mm]": "90.00",
    "height[mm]": "160.00"
  },
  {
    "title": "Livro do Desassossego",
    "subtitle": "",
    "author": "Bernardo Soares",
    "publisher": "Companhia das Letras",
    "collection": "",
    "genre": "poetry",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9788543802299",
    "Designer": "",
    "year": "1982",
    "pages": "480",
    "width[mm]": "90.00",
    "height[mm]": "160.00"
  },
  {
    "title": "Leaves Of Grass",
    "subtitle": "",
    "author": "Walt Whitman",
    "publisher": "Random House",
    "collection": "",
    "genre": "poetry",
    "language": "English",
    "country": "USA",
    "ISBN": "9780679642084",
    "Designer": "",
    "year": "1892",
    "pages": "176",
    "width[mm]": "90.00",
    "height[mm]": "160.00"
  },
  {
    "title": "A Madman's Diary",
    "subtitle": "And Other Stories",
    "author": "Lu Xun",
    "publisher": "Harvard University Press",
    "collection": "",
    "genre": "poetry",
    "language": "English",
    "country": "USA",
    "ISBN": "824812786",
    "Designer": "",
    "year": "1928",
    "pages": "136",
    "width[mm]": "90.00",
    "height[mm]": "160.00"
  },
  {
    "title": "The Man With The Golden Arm",
    "subtitle": "",
    "author": "Nelson Algren",
    "publisher": "Doubleday & Company, Inc",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "USA",
    "ISBN": "9781583220085",
    "Designer": "",
    "year": "1949",
    "pages": "343",
    "width[mm]": "120.00",
    "height[mm]": "190.00"
  },
  {
    "title": "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "subtitle": "",
    "author": "Robert Louis Stevenson",
    "publisher": "Longmans, Green and Co.",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781640320345",
    "Designer": "",
    "year": "1996",
    "pages": "196",
    "width[mm]": "120.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Le Deuxième Sexe",
    "subtitle": "",
    "author": "Simone De Beauvoir",
    "publisher": "Gallimard",
    "collection": "",
    "genre": "novel",
    "language": "French",
    "country": "France",
    "ISBN": "9782070323517",
    "Designer": "",
    "year": "1986",
    "pages": "978",
    "width[mm]": "120.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Les Misérables",
    "subtitle": "Première Part: Fantine",
    "author": "Victor Hugo",
    "publisher": "Bibebook",
    "collection": "",
    "genre": "novel",
    "language": "French",
    "country": "France",
    "ISBN": "9781846140495",
    "Designer": "",
    "year": "1862",
    "pages": "420",
    "width[mm]": "120.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Il Decameron",
    "subtitle": "",
    "author": "Giovanni Boccaccio",
    "publisher": "Pubblicata Alemar",
    "collection": "",
    "genre": "play",
    "language": "Italian",
    "country": "Italy",
    "ISBN": "9780136019701",
    "Designer": "",
    "year": "1573",
    "pages": "1058",
    "width[mm]": "135.00",
    "height[mm]": "225.00"
  },
  {
    "title": "Death of a Salesman",
    "subtitle": "",
    "author": "Arthur Miller",
    "publisher": "The Viking Press",
    "collection": "",
    "genre": "play",
    "language": "English",
    "country": "USA",
    "ISBN": "9780140481341",
    "Designer": "",
    "year": "1949",
    "pages": "185",
    "width[mm]": "135.00",
    "height[mm]": "225.00"
  },
  {
    "title": "Zorba the Greek",
    "subtitle": "",
    "author": "Nikos Kazantzakis",
    "publisher": "Simon & Schuster ",
    "collection": "",
    "genre": "Novel",
    "language": "Greek",
    "country": "Greece",
    "ISBN": "9780671851002",
    "Designer": "",
    "year": "1953",
    "pages": "320",
    "width[mm]": "110.00",
    "height[mm]": "170.00"
  },
  {
    "title": "The Wonderful Wizard of Oz",
    "subtitle": "",
    "author": "L. Frank Baum",
    "publisher": "George M. Hill Company",
    "collection": "The Oz books",
    "genre": "Fantasy, Children's novel",
    "language": "English",
    "country": "United States",
    "ISBN": "",
    "Designer": "",
    "year": "1900",
    "pages": "76",
    "width[mm]": "130.00",
    "height[mm]": "190.00"
  },
  {
    "title": "Vanity Fair",
    "subtitle": "",
    "author": "William M. Thaceray",
    "publisher": "Punch",
    "collection": "",
    "genre": "Satire",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "",
    "Designer": "",
    "year": "1847",
    "pages": "796",
    "width[mm]": "150.00",
    "height[mm]": "220.00"
  },
  {
    "title": "The Wild Duck",
    "subtitle": "",
    "author": "Henrik Ibsen ",
    "publisher": "The Walter Scott Publishing Co. Ltd.",
    "collection": "",
    "genre": "Drama",
    "language": "Norwegian",
    "country": "Norway",
    "ISBN": "",
    "Designer": "",
    "year": "1905",
    "pages": "96",
    "width[mm]": "115.00",
    "height[mm]": "180.00"
  },
  {
    "title": "The Trial",
    "subtitle": "",
    "author": "Franz Kafka",
    "publisher": "Schocken Books",
    "collection": "",
    "genre": "Fiction",
    "language": "German",
    "country": "Germany",
    "ISBN": "978-337-90-0058-1",
    "Designer": "",
    "year": "1925",
    "pages": "304",
    "width[mm]": "105.00",
    "height[mm]": "170.00"
  },
  {
    "title": "Faust",
    "subtitle": "",
    "author": "Johann Wolfgang von Goethe",
    "publisher": "Frederick Warne & Co., Ltd.",
    "collection": "",
    "genre": "Play,Epic",
    "language": "German",
    "country": "Germany",
    "ISBN": "978-038-50-3114-1",
    "Designer": "",
    "year": "1887",
    "pages": "512",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Romeu & Juliet",
    "subtitle": "An Excellent Conceited Tragedie",
    "author": "William Shakespeare",
    "publisher": "Saint Dunflanes Church-yard",
    "collection": "",
    "genre": "Tragedy",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "978-013-35-5629-2",
    "Designer": "",
    "year": "1609",
    "pages": "173",
    "width[mm]": "110.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Frankenstein",
    "subtitle": "The Modern Prometheus",
    "author": "Mary Shelley",
    "publisher": "Lackington, Hughes, Harding, Mavor & Jone",
    "collection": "",
    "genre": "Gothic novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "978-014-04-3237-4",
    "Designer": "",
    "year": "1818",
    "pages": "280",
    "width[mm]": "120.00",
    "height[mm]": "190.00"
  },
  {
    "title": "The Essays",
    "subtitle": "or Moral, Politike and Militaire Discourles",
    "author": "Michael Seignevr de Montaigne",
    "publisher": "Simon Millanges, Jean Richer",
    "collection": "",
    "genre": "Essay",
    "language": "French",
    "country": "France",
    "ISBN": "978-087-96-8311-5",
    "Designer": "",
    "year": "1685",
    "pages": "812",
    "width[mm]": "130.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Ficciones",
    "subtitle": "",
    "author": "Jorge Luis Borges",
    "publisher": "EMECÉ",
    "collection": "",
    "genre": "Short-story",
    "language": "Spanish",
    "country": "Argentina",
    "ISBN": "978-950-04-0205-7",
    "Designer": "",
    "year": "1956",
    "pages": "174",
    "width[mm]": "155.00",
    "height[mm]": "240.00"
  },
  {
    "title": "O Mestre e Margarita",
    "subtitle": "",
    "author": "Mikhail Bulgakov",
    "publisher": "YMCA Press",
    "collection": "",
    "genre": "novel",
    "language": "Russian ",
    "country": "Russia",
    "ISBN": "978-972-23-5444-8",
    "Designer": "",
    "year": "1967",
    "pages": "422",
    "width[mm]": "160.00",
    "height[mm]": "240.00"
  },
  {
    "title": "The Sound and the Fury",
    "subtitle": "",
    "author": "William Faulkner",
    "publisher": "Harrison Smith",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "USA",
    "ISBN": "",
    "Designer": "",
    "year": "1929",
    "pages": "326",
    "width[mm]": "160.00",
    "height[mm]": "240.00"
  },
  {
    "title": "The Unconsoled",
    "subtitle": "",
    "author": "Kazuo Ishiguro",
    "publisher": "Faber and Faber",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "UK",
    "ISBN": " 0-571-17718-2",
    "Designer": "",
    "year": "1995",
    "pages": "535",
    "width[mm]": "126.00",
    "height[mm]": "200.00"
  },
  {
    "title": "A noite dos proletários",
    "subtitle": ":arquivos do sonho operário",
    "author": "Jacques Rancière",
    "publisher": "Antígona",
    "collection": "",
    "genre": "Politics",
    "language": "Portuguese",
    "country": "France",
    "ISBN": "9789726082200",
    "Designer": "",
    "year": "1981",
    "pages": "378",
    "width[mm]": "110.00",
    "height[mm]": "170.00"
  },
  {
    "title": "Discipline and Punish",
    "subtitle": "The Birth of the Prison",
    "author": "Michel Foucault",
    "publisher": "Vintage",
    "collection": "",
    "genre": "Philosophy ",
    "language": "English",
    "country": "France",
    "ISBN": "9780679752554",
    "Designer": "",
    "year": "1975",
    "pages": "352",
    "width[mm]": "110.00",
    "height[mm]": "170.00"
  },
  {
    "title": "Ensaio Sobre a Cegueira",
    "subtitle": "",
    "author": "José Saramago ",
    "publisher": "Editorial Caminho",
    "collection": "",
    "genre": "Romance",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789722110211",
    "Designer": "",
    "year": "1995",
    "pages": "310",
    "width[mm]": "126.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Jude the Obscure",
    "subtitle": "",
    "author": "Thomas Hardy",
    "publisher": "Dover Publications",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "UK",
    "ISBN": "9780486452432",
    "Designer": "",
    "year": "1895",
    "pages": "310",
    "width[mm]": "126.00",
    "height[mm]": "200.00"
  },
  {
    "title": "História de Menina e Moça",
    "subtitle": "",
    "author": "Bernardim Ribeiro",
    "publisher": "",
    "collection": "",
    "genre": "Novela",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789896350703",
    "Designer": "",
    "year": "1554",
    "pages": "144",
    "width[mm]": "126.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Jakob von Gunten",
    "subtitle": "",
    "author": "Robert Walser",
    "publisher": "New York Review Books Classics",
    "collection": "",
    "genre": "Novel ",
    "language": "English",
    "country": "Germany",
    "ISBN": "9780940322219",
    "Designer": "",
    "year": "1909",
    "pages": "176",
    "width[mm]": "160.00",
    "height[mm]": "240.00"
  },
  {
    "title": "Independent People",
    "subtitle": "",
    "author": "Halldór Laxness",
    "publisher": "Vintage",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "Iceland",
    "ISBN": "9780679767923",
    "Designer": "",
    "year": "1934",
    "pages": "482",
    "width[mm]": "110.00",
    "height[mm]": "170.00"
  },
  {
    "title": "The Canterbury Tales",
    "subtitle": "",
    "author": "Geoffrey Chaucer ",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "Satire",
    "language": "Midddle English",
    "country": "England",
    "ISBN": "9780141393216",
    "Designer": "",
    "year": "1392",
    "pages": "528",
    "width[mm]": "137.00",
    "height[mm]": "207.00"
  },
  {
    "title": "Dead Souls",
    "subtitle": "",
    "author": "Nikolai Gógol ",
    "publisher": "Wordsworth Books Ltd.",
    "collection": "",
    "genre": "Fiction",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9781840226379",
    "Designer": "",
    "year": "1842",
    "pages": "496",
    "width[mm]": "124.00",
    "height[mm]": "196.00"
  },
  {
    "title": "Hyperion",
    "subtitle": "oder, Der Eremit in Griechenland",
    "author": "Friedrich Hölderlin",
    "publisher": "Tredition Classics",
    "collection": "",
    "genre": "Epistolary novel",
    "language": "German",
    "country": "Germany",
    "ISBN": "9783847292142",
    "Designer": "",
    "year": "1797",
    "pages": "160",
    "width[mm]": "525.00",
    "height[mm]": "800.00"
  },
  {
    "title": "Metamorphoses",
    "subtitle": "",
    "author": "Ovid ",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "narrative poetry ",
    "language": "Latin",
    "country": "Ancient Rome",
    "ISBN": "9780141394619",
    "Designer": "",
    "year": "8 d.C.",
    "pages": "768",
    "width[mm]": "136.00",
    "height[mm]": "203.00"
  },
  {
    "title": "Mother",
    "subtitle": "",
    "author": "Maxim Gorky",
    "publisher": "Repro Knowledgcast Ltd",
    "collection": "",
    "genre": "Fiction",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9788180320330",
    "Designer": "",
    "year": "1907",
    "pages": "358",
    "width[mm]": "133.00",
    "height[mm]": "203.00"
  },
  {
    "title": "Os Passos Perdidos",
    "subtitle": "",
    "author": "Alejo Carpentier ",
    "publisher": "Edições 70",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United States",
    "ISBN": "9789724412207",
    "Designer": "",
    "year": "1953",
    "pages": "272",
    "width[mm]": "153.00",
    "height[mm]": "230.00"
  },
  {
    "title": "The Monk",
    "subtitle": "",
    "author": "Matthew Lewis",
    "publisher": "e-artnow",
    "collection": "",
    "genre": "Gothic novel",
    "language": "English",
    "country": "England",
    "ISBN": "9788027305711",
    "Designer": "",
    "year": "1796",
    "pages": "228",
    "width[mm]": "152.00",
    "height[mm]": "229.00"
  },
  {
    "title": "Seara de Vento",
    "subtitle": "",
    "author": "Manuel da Fonseca ",
    "publisher": "Editorial Caminho",
    "collection": "",
    "genre": "novel",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789722100533",
    "Designer": "",
    "year": "1988",
    "pages": "212",
    "width[mm]": "134.00",
    "height[mm]": "209.00"
  },
  {
    "title": "Tom Sawyer",
    "subtitle": "",
    "author": "Mark Twain",
    "publisher": "Editora Guerra & Paz",
    "collection": "",
    "genre": "novel",
    "language": "English",
    "country": "United States",
    "ISBN": "9789897022715",
    "Designer": "",
    "year": "1876",
    "pages": "272",
    "width[mm]": "149.00",
    "height[mm]": "229.00"
  },
  {
    "title": "Viagens na Minha Terra",
    "subtitle": "",
    "author": "Almeida Garret",
    "publisher": "Livraria Civilização Editora",
    "collection": "Novos Clássicos",
    "genre": "Novel",
    "language": "Português",
    "country": "Portugal",
    "ISBN": "9789722636148",
    "Designer": "",
    "year": "1845",
    "pages": "232",
    "width[mm]": "149.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Aeneid",
    "subtitle": "",
    "author": "Virgil",
    "publisher": "Bolchazy-Carducci Publishers",
    "collection": "",
    "genre": "Fantasy",
    "language": "Latin",
    "country": "",
    "ISBN": "978-086-5-16433-8",
    "Designer": "",
    "year": "1999",
    "pages": "518",
    "width[mm]": "159.75",
    "height[mm]": "212.34"
  },
  {
    "title": "Lolita",
    "subtitle": "",
    "author": "Vladimir Nabokov",
    "publisher": "Relógio D'Água",
    "collection": "Ficções",
    "genre": "Romance",
    "language": "Português",
    "country": "U.K",
    "ISBN": "978-972-0-04957-5",
    "Designer": "",
    "year": "2013",
    "pages": "360",
    "width[mm]": "151.00",
    "height[mm]": "231.00"
  },
  {
    "title": "Os Maias",
    "subtitle": "",
    "author": "Eça de Queirós",
    "publisher": "Porto Editora",
    "collection": "Clássicos Porto Editora",
    "genre": "Romance",
    "language": "Inglês",
    "country": "Portugal",
    "ISBN": "978-972-0-04957-5",
    "Designer": "",
    "year": "2020",
    "pages": "720",
    "width[mm]": "128.00",
    "height[mm]": "198.00"
  },
  {
    "title": "Panegyric",
    "subtitle": "",
    "author": "Guy Debord",
    "publisher": "Verso",
    "collection": "",
    "genre": "",
    "language": "Inglês",
    "country": "",
    "ISBN": "1844673537",
    "Designer": "",
    "year": "2009",
    "pages": "181",
    "width[mm]": "128.52",
    "height[mm]": "195.33"
  },
  {
    "title": "Pastoralia",
    "subtitle": "",
    "author": "George Saunders",
    "publisher": "Riverhead Books",
    "collection": "",
    "genre": "",
    "language": "Inglês",
    "country": "EUA",
    "ISBN": "1573228729",
    "Designer": "",
    "year": "2001",
    "pages": "188",
    "width[mm]": "130.56",
    "height[mm]": "202.69"
  },
  {
    "title": "The Castle",
    "subtitle": "",
    "author": "Franz Kafka",
    "publisher": "Schocken",
    "collection": "The Schocken Kafka Library ",
    "genre": "Ficção",
    "language": "Inglês",
    "country": "",
    "ISBN": "805211063",
    "Designer": "",
    "year": "1998",
    "pages": "352",
    "width[mm]": "130.05",
    "height[mm]": "202.95"
  },
  {
    "title": "The End Of The World News",
    "subtitle": "",
    "author": "Anthony Burgess",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "",
    "language": "Inglês",
    "country": "",
    "ISBN": "140067469",
    "Designer": "",
    "year": "1983",
    "pages": "389",
    "width[mm]": "127.00",
    "height[mm]": "177.80"
  },
  {
    "title": "The Golden Notebook",
    "subtitle": "",
    "author": "Doris Lessing",
    "publisher": "Harper Perennial Modern Classics",
    "collection": "",
    "genre": "",
    "language": "Inglês",
    "country": "",
    "ISBN": "9780007247202",
    "Designer": "",
    "year": "2007",
    "pages": "576",
    "width[mm]": "129.03",
    "height[mm]": "197.10"
  },
  {
    "title": "Le Misanthrope",
    "subtitle": "",
    "author": "Molière",
    "publisher": "Dover Publications",
    "collection": "",
    "genre": "Drama",
    "language": "Inglês",
    "country": "França",
    "ISBN": "9780486270654",
    "Designer": "",
    "year": "1992",
    "pages": "64",
    "width[mm]": "132.33",
    "height[mm]": "210.31"
  },
  {
    "title": "The Lost Honor of Labor",
    "subtitle": "Socialism of the Producers as Logical Impossibility",
    "author": "Robert Kurz",
    "publisher": "Antígona",
    "collection": "",
    "genre": "",
    "language": "Português",
    "country": "",
    "ISBN": "978-9726083139",
    "Designer": "",
    "year": "",
    "pages": "160",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "The Old Man and the Sea",
    "subtitle": "",
    "author": "Ernest Hemingway",
    "publisher": "Charles Scribers Sons",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "U.K",
    "ISBN": "",
    "Designer": "",
    "year": "1990",
    "pages": "",
    "width[mm]": "100.00",
    "height[mm]": "140.00"
  },
  {
    "title": "In Cold Blood ",
    "subtitle": "",
    "author": "Truman Capote",
    "publisher": "Penguin Books",
    "collection": "Penguin Books",
    "genre": "Drama",
    "language": "English",
    "country": "U.S.A",
    "ISBN": "9780241956830",
    "Designer": "",
    "year": "1965",
    "pages": "352",
    "width[mm]": "145.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Foucalts Pendulum",
    "subtitle": "",
    "author": "Umberto Eco",
    "publisher": "Kurt Wolff Book & Harcourt Brace Javonovich, Publishers. ",
    "collection": "",
    "genre": "Fiction",
    "language": "Italian",
    "country": "Italy",
    "ISBN": "8845215911",
    "Designer": "",
    "year": "1988",
    "pages": "",
    "width[mm]": "100.00",
    "height[mm]": "140.00"
  },
  {
    "title": "A Serpente ",
    "subtitle": "",
    "author": "Stig Dagerman",
    "publisher": "Antígona",
    "collection": "",
    "genre": "Drama",
    "language": "Swedish",
    "country": "Sweden",
    "ISBN": "",
    "Designer": "",
    "year": "",
    "pages": "",
    "width[mm]": "145.00",
    "height[mm]": "200.00"
  },
  {
    "title": "News From Nowhere",
    "subtitle": "",
    "author": "William Morris",
    "publisher": "Robert Brothers",
    "collection": "",
    "genre": "Utopian Romance",
    "language": "English",
    "country": "U.K",
    "ISBN": "9788586469688",
    "Designer": "",
    "year": "",
    "pages": "",
    "width[mm]": "180.00",
    "height[mm]": "230.00"
  },
  {
    "title": "A Grande Bebedeira ",
    "subtitle": "",
    "author": "Réne Deumal",
    "publisher": "Dois Dias",
    "collection": "",
    "genre": "Novel",
    "language": "Português (t)",
    "country": "França",
    "ISBN": "9789899736283",
    "Designer": "",
    "year": "1932-1933",
    "pages": "160",
    "width[mm]": "100.00",
    "height[mm]": "140.00"
  },
  {
    "title": "As Mil e Uma Noite",
    "subtitle": "Contos Arabes",
    "author": "",
    "publisher": "Typographia de A.J da Silva Teixeira",
    "collection": "",
    "genre": "",
    "language": "Arabian/Portuguese",
    "country": "Portugal",
    "ISBN": "",
    "Designer": "",
    "year": "1881",
    "pages": "",
    "width[mm]": "170.00",
    "height[mm]": "250.00"
  },
  {
    "title": "Solaris ",
    "subtitle": "",
    "author": "Stanislaw Lem ",
    "publisher": "Mon, Walker U.S",
    "collection": "",
    "genre": "Science Fiction",
    "language": "Polish",
    "country": "Poland",
    "ISBN": "9780486280615",
    "Designer": "",
    "year": "1961",
    "pages": "272",
    "width[mm]": "145.00",
    "height[mm]": "200.00"
  },
  {
    "title": "The Adventures of Huckleberry Finn",
    "subtitle": "",
    "author": "Mark Twain",
    "publisher": "Charles L.Webster and company",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "U.S.A",
    "ISBN": "9780486280615",
    "Designer": "",
    "year": "1885",
    "pages": "",
    "width[mm]": "145.00",
    "height[mm]": "225.00"
  },
  {
    "title": "In Search of Lost Time ",
    "subtitle": "",
    "author": "Marcel Proust",
    "publisher": "Grasset and Gallimard",
    "collection": "",
    "genre": "Novel",
    "language": "Franch",
    "country": "France",
    "ISBN": "9780141180335",
    "Designer": "",
    "year": "1913-1927",
    "pages": "4215",
    "width[mm]": "100.00",
    "height[mm]": "140.00"
  },
  {
    "title": "The Steppe and Other Stories",
    "subtitle": "",
    "author": "Anton Tchékhov",
    "publisher": "Penguin Classics",
    "collection": "",
    "genre": "Fiction/ Classics",
    "language": "English",
    "country": "Russia",
    "ISBN": "9780140447859",
    "Designer": "",
    "year": "1888",
    "pages": "416",
    "width[mm]": "100.00",
    "height[mm]": "160.00"
  },
  {
    "title": "Daisy Miller",
    "subtitle": "",
    "author": "Henry James",
    "publisher": "Harper & Brothers",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781592243006",
    "Designer": "",
    "year": "1879",
    "pages": "43",
    "width[mm]": "115.00",
    "height[mm]": "195.00"
  },
  {
    "title": "Invisible Man",
    "subtitle": "",
    "author": "Ralph Ellison",
    "publisher": "Random House",
    "collection": "",
    "genre": "Social Comment",
    "language": "English",
    "country": "United States",
    "ISBN": "9780679601395",
    "Designer": "",
    "year": "1952",
    "pages": "581",
    "width[mm]": "120.00",
    "height[mm]": "210.00"
  },
  {
    "title": "The Book of Embraces",
    "subtitle": "",
    "author": "Eduardo Galeano",
    "publisher": "L&PM Editores",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "United States",
    "ISBN": "9788525428158",
    "Designer": "",
    "year": "1989",
    "pages": "288",
    "width[mm]": "130.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Children of the Days",
    "subtitle": "",
    "author": "Eduardo Galeano",
    "publisher": "Nation Books",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "United States",
    "ISBN": "9781568587479",
    "Designer": "",
    "year": "2012",
    "pages": "423",
    "width[mm]": "120.00",
    "height[mm]": "200.00"
  },
  {
    "title": "Selected Stories",
    "subtitle": "",
    "author": "Anton Tchékhov",
    "publisher": "Bravo Ltd",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "Russia",
    "ISBN": "9780553381009",
    "Designer": "",
    "year": "1903",
    "pages": "496",
    "width[mm]": "120.00",
    "height[mm]": "180.00"
  },
  {
    "title": "The Idiot",
    "subtitle": "",
    "author": "Fyodor Dostoevsky",
    "publisher": "Modern Library",
    "collection": "",
    "genre": "Fiction",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9780553213522",
    "Designer": "",
    "year": "1869",
    "pages": "667",
    "width[mm]": "135.00",
    "height[mm]": "230.00"
  },
  {
    "title": "The Possessed",
    "subtitle": "",
    "author": "Fyodor Dostoevsky",
    "publisher": "Barnes & Noble Classics",
    "collection": "",
    "genre": "Philosophical novel",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9781593082505",
    "Designer": "",
    "year": "1871",
    "pages": "768",
    "width[mm]": "148.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Utopia",
    "subtitle": "",
    "author": "Thomas More",
    "publisher": "",
    "collection": "",
    "genre": "Satire, Fantasy Fiction",
    "language": "Latin",
    "country": "Netherlands",
    "ISBN": "9781512093384",
    "Designer": "",
    "year": "1516",
    "pages": "359",
    "width[mm]": "110.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Memoirs of Hadrian",
    "subtitle": "",
    "author": "Marguerite Yourcenar",
    "publisher": "Plon",
    "collection": "",
    "genre": "Historical novel",
    "language": "French",
    "country": "France",
    "ISBN": "9780374529260",
    "Designer": "",
    "year": "1951",
    "pages": "323",
    "width[mm]": "110.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Le Comte de Monte-Cristo",
    "subtitle": "",
    "author": "Alexandre Dumas",
    "publisher": "Penguin Classics",
    "collection": "",
    "genre": "Historical novel, Adventure",
    "language": "French",
    "country": "France",
    "ISBN": "9780199219650",
    "Designer": "",
    "year": "1884",
    "pages": "1138",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "The Death Of Ivan Ilyich",
    "subtitle": "Master and man",
    "author": "Leo Tolstoy",
    "publisher": "Modern Library",
    "collection": "2004 Modern Library Paperback Edition",
    "genre": "Fiction, Philosophy",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9780375760990",
    "Designer": "",
    "year": "1846",
    "pages": "160",
    "width[mm]": "131.3mm",
    "height[mm]": "201.93mm"
  },
  {
    "title": "A Room With a View",
    "subtitle": "",
    "author": "E.M. Forster",
    "publisher": "Edward Arnold",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9780141199825",
    "Designer": "",
    "year": "1908",
    "pages": "321",
    "width[mm]": "128 mm",
    "height[mm]": "195 mm"
  },
  {
    "title": "Hadji Murat",
    "subtitle": "",
    "author": "Leo Tolstoy",
    "publisher": "Media type Print",
    "collection": "",
    "genre": "Historical fiction",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9789896411060",
    "Designer": "",
    "year": "1912",
    "pages": "134",
    "width[mm]": "152 mm",
    "height[mm]": "232 mm"
  },
  {
    "title": "Berlin Alexanderplatz",
    "subtitle": "",
    "author": "Alfred Döblin",
    "publisher": "S. Fischer Verlag",
    "collection": "",
    "genre": "Novel",
    "language": "German",
    "country": "Germany",
    "ISBN": "9783423310864",
    "Designer": "",
    "year": "1929",
    "pages": "592",
    "width[mm]": "158 mm",
    "height[mm]": "233 mm"
  },
  {
    "title": "Tender Is the Night",
    "subtitle": "",
    "author": "F. Scott Fitzgerald",
    "publisher": "Charles Scribner’s Sons",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United States",
    "ISBN": "9780241341483",
    "Designer": "",
    "year": "1934",
    "pages": "368",
    "width[mm]": "129 mm",
    "height[mm]": "197 mm"
  },
  {
    "title": "The Man in the High Castle",
    "subtitle": "",
    "author": "Philip K. Dick",
    "publisher": "Putnam",
    "collection": "",
    "genre": "Alternate history",
    "language": "English",
    "country": "United States",
    "ISBN": "9780241968093",
    "Designer": "",
    "year": "1962",
    "pages": "256",
    "width[mm]": "111 mm",
    "height[mm]": "179 mm"
  },
  {
    "title": "Le città invisibili",
    "subtitle": "",
    "author": "Italo Calvino",
    "publisher": "Giulio Einaudi Editore",
    "collection": "",
    "genre": "Novel",
    "language": "Italian",
    "country": "Italy",
    "ISBN": "9789722057097",
    "Designer": "",
    "year": "1972",
    "pages": "176",
    "width[mm]": "156 mm",
    "height[mm]": "232 mm"
  },
  {
    "title": "The Unbearable Lightness of Being",
    "subtitle": "",
    "author": "Milan Kundera",
    "publisher": "Gallimard",
    "collection": "",
    "genre": "Philosophical fiction, Magical realism",
    "language": "Czech",
    "country": "France",
    "ISBN": "9780571135394",
    "Designer": "",
    "year": "1984",
    "pages": "320",
    "width[mm]": "126 mm",
    "height[mm]": "197 mm"
  },
  {
    "title": "Schachnovelle",
    "subtitle": "",
    "author": "Stefan Zweig",
    "publisher": "Penguin Random House Canada",
    "collection": "",
    "genre": "Novella",
    "language": "German",
    "country": "Aystria",
    "ISBN": "9781291388213",
    "Designer": "",
    "year": "1964",
    "pages": "66",
    "width[mm]": "148mm",
    "height[mm]": "209.8 mm"
  },
  {
    "title": "Pippi Longstocking",
    "subtitle": "",
    "author": "Astrid Lindgren",
    "publisher": "The Viking Press",
    "collection": "",
    "genre": "Novel",
    "language": "Swedish",
    "country": "Sweden",
    "ISBN": "9780140309577",
    "Designer": "",
    "year": "1945",
    "pages": "160",
    "width[mm]": "144.40",
    "height[mm]": "210.00"
  },
  {
    "title": "Dracula",
    "subtitle": "",
    "author": "Bram Stoker",
    "publisher": "Three Owls Edition",
    "collection": "",
    "genre": "Horror",
    "language": "English",
    "country": "Ireland",
    "ISBN": "9780440302315",
    "Designer": "",
    "year": "1897",
    "pages": "418",
    "width[mm]": "148.00",
    "height[mm]": "210.00"
  },
  {
    "title": "The Grapes of Wrath",
    "subtitle": "",
    "author": "John Steinbeck",
    "publisher": "The Viking Press",
    "collection": "",
    "genre": "Romance",
    "language": "English",
    "country": "USA",
    "ISBN": "9781000349584",
    "Designer": "",
    "year": "1938",
    "pages": "464",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Sonetos",
    "subtitle": "",
    "author": "Antero de Quental",
    "publisher": "Imprensa da Universidade",
    "collection": "",
    "genre": "Poetry",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9780885500300",
    "Designer": "",
    "year": "1886",
    "pages": "125",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Othello",
    "subtitle": "",
    "author": "William Shakespeare",
    "publisher": "Bloomsbury",
    "collection": "",
    "genre": "Tragedy",
    "language": "English",
    "country": "England",
    "ISBN": "9702140805557",
    "Designer": "",
    "year": "1603",
    "pages": "320",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Children of Gebelawi",
    "subtitle": "",
    "author": "Naguib Mahfouz",
    "publisher": "Three Continents Press",
    "collection": "",
    "genre": "Novel",
    "language": "Arabic",
    "country": "Egypt",
    "ISBN": "9781253734114",
    "Designer": "",
    "year": "1960",
    "pages": "355",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Histoires Brisées",
    "subtitle": "",
    "author": "Paul Valéry",
    "publisher": "Gallimard",
    "collection": "",
    "genre": "Novel",
    "language": "French",
    "country": "France",
    "ISBN": "9783133463510",
    "Designer": "",
    "year": "1950",
    "pages": "192",
    "width[mm]": "138.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Lés Hérésies",
    "subtitle": "",
    "author": "Raoul Vaneigem",
    "publisher": "Presses Universitaires de France",
    "collection": "",
    "genre": "Poetry",
    "language": "French",
    "country": "France",
    "ISBN": "9782130460510",
    "Designer": "",
    "year": "1996",
    "pages": "128",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "The Murder at the Vicarage",
    "subtitle": "",
    "author": "Agatha Christie",
    "publisher": "The Crime Club",
    "collection": "",
    "genre": "Crime",
    "language": "English",
    "country": "England",
    "ISBN": "9780008196516",
    "Designer": "",
    "year": "1930",
    "pages": "304",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Death in Venice",
    "subtitle": "",
    "author": "Thomas Mann",
    "publisher": "Dover Thrift",
    "collection": "",
    "genre": "Novel",
    "language": "German",
    "country": "Germany",
    "ISBN": "9781784875015",
    "Designer": "",
    "year": "1912",
    "pages": "368",
    "width[mm]": "140.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Naked Lunch",
    "subtitle": "",
    "author": "William Burroughs",
    "publisher": "Penguin Books",
    "collection": "Penguin Morden Classics",
    "genre": "Novel",
    "language": "English",
    "country": "France",
    "ISBN": "9783548028439",
    "Designer": "",
    "year": "1959",
    "pages": "304",
    "width[mm]": "100.00",
    "height[mm]": "180.00"
  },
  {
    "title": "King Lear",
    "subtitle": "",
    "author": "William Shakespeare",
    "publisher": "Penguin Books",
    "collection": "Penguin Classics",
    "genre": "Tragedie",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9780141396460",
    "Designer": "",
    "year": "1606",
    "pages": "368",
    "width[mm]": "105.00",
    "height[mm]": "195.00"
  },
  {
    "title": "Divina Comédia",
    "subtitle": "",
    "author": "Dante Alighieri",
    "publisher": "Quetzal Editores",
    "collection": "",
    "genre": "Tragedie",
    "language": "Italian",
    "country": "Florentine Republic",
    "ISBN": "9789725649428",
    "Designer": "",
    "year": "1472",
    "pages": "896",
    "width[mm]": "110.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Capitão Mihális",
    "subtitle": "Liberdade ou Morte",
    "author": "Nikos Kazantzakis",
    "publisher": "Grua Livros",
    "collection": "",
    "genre": "Fiction",
    "language": "Greek",
    "country": "Greece",
    "ISBN": "9788561578275",
    "Designer": "",
    "year": "1953",
    "pages": "472",
    "width[mm]": "110.00",
    "height[mm]": "185.00"
  },
  {
    "title": "Midnight's Children",
    "subtitle": "",
    "author": "Salman Rushdie",
    "publisher": "Vintage",
    "collection": "",
    "genre": "Magical Realism",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9780099578512",
    "Designer": "",
    "year": "1801",
    "pages": "446",
    "width[mm]": "110.00",
    "height[mm]": "185.00"
  },
  {
    "title": "Moby Dick",
    "subtitle": "The Whale",
    "author": "Herman Melville",
    "publisher": "Relógio d'Àgua",
    "collection": "Classics",
    "genre": "Novel",
    "language": "English",
    "country": "United States",
    "ISBN": "9789727088539",
    "Designer": "",
    "year": "1851",
    "pages": "616",
    "width[mm]": "110.00",
    "height[mm]": "185.00"
  },
  {
    "title": "North and South",
    "subtitle": "",
    "author": "Elizabeth Gaskell",
    "publisher": "Wordsworth Editions Ltd",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "9781853260933",
    "Designer": "",
    "year": "1854",
    "pages": "480",
    "width[mm]": "115.00",
    "height[mm]": "175.00"
  },
  {
    "title": "O Capital",
    "subtitle": "",
    "author": "Karl Marx",
    "publisher": "Edições 70",
    "collection": "Biblioteca de Teoria Pólitica",
    "genre": "Treatise",
    "language": "German",
    "country": "Germany",
    "ISBN": "9789724419985",
    "Designer": "",
    "year": "1867",
    "pages": "528",
    "width[mm]": "145.00",
    "height[mm]": "205.00"
  },
  {
    "title": "We",
    "subtitle": "",
    "author": "Yevgeny Zamyatin",
    "publisher": "Penguin Books",
    "collection": "Penguin Classics",
    "genre": "Novel",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9780140185850",
    "Designer": "",
    "year": "1988",
    "pages": "256",
    "width[mm]": "110.00",
    "height[mm]": "185.00"
  },
  {
    "title": "Day of the Oprichnik",
    "subtitle": "",
    "author": "Vladimir Sorokin",
    "publisher": "Penguin Books",
    "collection": "Penguin Morden Classics",
    "genre": "Novel",
    "language": "Russian",
    "country": "Russia",
    "ISBN": "9780241355114",
    "Designer": "",
    "year": "2006",
    "pages": "208",
    "width[mm]": "130.00",
    "height[mm]": "180.00"
  },
  {
    "title": "Ulysses",
    "subtitle": "",
    "author": "James Joyce",
    "publisher": "Shakespeare and Company",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "Ireland",
    "ISBN": "394743121",
    "Designer": "",
    "year": "1922",
    "pages": "730",
    "width[mm]": "156.00",
    "height[mm]": "233.20"
  },
  {
    "title": "The Big Sleep",
    "subtitle": "",
    "author": "Raymond Chandler",
    "publisher": "Alfred A. Knopf",
    "collection": "",
    "genre": "Crime Novel",
    "language": "English",
    "country": "USA",
    "ISBN": "394758285",
    "Designer": "",
    "year": "1939",
    "pages": "277",
    "width[mm]": "130.30",
    "height[mm]": "201.70"
  },
  {
    "title": "A Origem",
    "subtitle": "",
    "author": "Graça de Pina Morais",
    "publisher": "Sociedade De Expansão Cultural",
    "collection": "",
    "genre": "Romance ",
    "language": "Portuguese",
    "country": "Portugal",
    "ISBN": "9789726080527",
    "Designer": "",
    "year": "1958",
    "pages": "252",
    "width[mm]": "130.00",
    "height[mm]": "208.00"
  },
  {
    "title": "The Lost Boy",
    "subtitle": "",
    "author": "Thomas Wolfe",
    "publisher": "Harper & Row, publishers",
    "collection": "",
    "genre": "Novella, Fiction, Autobiographical novel",
    "language": "English",
    "country": "USA",
    "ISBN": "807820636",
    "Designer": "",
    "year": "1955",
    "pages": "95",
    "width[mm]": "152.40",
    "height[mm]": "247.70"
  },
  {
    "title": "Pedro Paramo",
    "subtitle": "",
    "author": "Juan Rulfo",
    "publisher": "Fondo de Cultura Economica",
    "collection": "",
    "genre": "Romance Regionalista",
    "language": "Spanish",
    "country": "Mexico",
    "ISBN": "802133908",
    "Designer": "",
    "year": "1955",
    "pages": "128",
    "width[mm]": "129.50",
    "height[mm]": "193.00"
  },
  {
    "title": "The Baron in the Trees",
    "subtitle": "",
    "author": "Italo Calvino",
    "publisher": "Giulio Einaudi",
    "collection": "",
    "genre": "Fiction Novel",
    "language": "Italian",
    "country": "Italy",
    "ISBN": "1599211823",
    "Designer": "",
    "year": "1957",
    "pages": "224",
    "width[mm]": "134.60",
    "height[mm]": "200.70"
  },
  {
    "title": "The Man Without Qualities",
    "subtitle": "",
    "author": "Robert Musil",
    "publisher": "Rowohlt Verlag",
    "collection": "",
    "genre": "Novel, Philosophical fiction",
    "language": "German",
    "country": "Germany",
    "ISBN": "679767878",
    "Designer": "",
    "year": "1943",
    "pages": "752",
    "width[mm]": "131.30",
    "height[mm]": "203.20"
  },
  {
    "title": "The Mathnawi",
    "subtitle": "",
    "author": "Jalal ad-din Rumi",
    "publisher": "M.G. Publishers",
    "collection": "",
    "genre": "Poetry",
    "language": "Persian",
    "country": "Balkh (present-day Afghanistan)",
    "ISBN": "62509594",
    "Designer": "",
    "year": "1258-1273",
    "pages": "416",
    "width[mm]": "134.90",
    "height[mm]": "203.20"
  },
  {
    "title": "The Sound of the Mountain ",
    "subtitle": "",
    "author": "Yasunari Kawabata",
    "publisher": "Knopf",
    "collection": "",
    "genre": "Novel",
    "language": "Japanese",
    "country": "Japan",
    "ISBN": "679762647",
    "Designer": "",
    "year": "1949",
    "pages": "288",
    "width[mm]": "131.80",
    "height[mm]": "202.90"
  },
  {
    "title": "Wuthering Heights",
    "subtitle": "",
    "author": "Emily Bronte",
    "publisher": "Thomas Cautley Newby, PUBLISHER",
    "collection": "",
    "genre": "Tragedy",
    "language": "English",
    "country": "UK",
    "ISBN": "141439556",
    "Designer": "",
    "year": "1847",
    "pages": "416",
    "width[mm]": "127.00",
    "height[mm]": "195.60"
  },
  {
    "title": "Charade",
    "subtitle": "",
    "author": "John Mortimer",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "Crime Novel",
    "language": "English",
    "country": "UK",
    "ISBN": "978-0140092677",
    "Designer": "",
    "year": "1988",
    "pages": "192",
    "width[mm]": "127.00",
    "height[mm]": "177.00"
  },
  {
    "title": "Dom Casmurro",
    "subtitle": "",
    "author": "Machado de Assis",
    "publisher": "Dom Quixote",
    "collection": "",
    "genre": "Romance",
    "language": "Português",
    "country": "Brasil",
    "ISBN": "9789722037464",
    "Designer": "",
    "year": "2009",
    "pages": "312",
    "width[mm]": "156.00",
    "height[mm]": "236.00"
  },
  {
    "title": "The Magic Mountain",
    "subtitle": "",
    "author": "Thomas Mann",
    "publisher": "Dead Authors Society",
    "collection": "",
    "genre": "Ficção",
    "language": "English",
    "country": "Germany",
    "ISBN": "9781773230139",
    "Designer": "",
    "year": "2016",
    "pages": "492",
    "width[mm]": "229.00",
    "height[mm]": "152.00"
  },
  {
    "title": "The Complete Fairy Tales and Stories",
    "subtitle": "",
    "author": "Hans Christian Andersen",
    "publisher": "Anchor Folktale Library",
    "collection": "",
    "genre": "Fairy Tale, Children's literature",
    "language": "English",
    "country": "Denmark",
    "ISBN": "978-0385189514",
    "Designer": "",
    "year": "1983",
    "pages": "1120",
    "width[mm]": "149.86",
    "height[mm]": "232.66"
  },
  {
    "title": "Journey to the end of the Night",
    "subtitle": "",
    "author": "Louis-Ferdinand Céline",
    "publisher": "NEW DIRECTIONS PUBLISHING CORPORATION",
    "collection": "",
    "genre": "Novel, Fiction",
    "language": "English",
    "country": "France",
    "ISBN": "9780811216548",
    "Designer": "",
    "year": "2006",
    "pages": "464",
    "width[mm]": "131.00",
    "height[mm]": "201.00"
  },
  {
    "title": "Madame Bouvary",
    "subtitle": "",
    "author": "Gustave Flaubert",
    "publisher": "Wordsworth Editions Ltd",
    "collection": "",
    "genre": "Romance",
    "language": "English",
    "country": "France",
    "ISBN": "978-1853260780",
    "Designer": "",
    "year": "1998",
    "pages": "304",
    "width[mm]": "126.49",
    "height[mm]": "197.61"
  },
  {
    "title": "L' amour Fou",
    "subtitle": "",
    "author": "André Breton",
    "publisher": "Gallimard.",
    "collection": "",
    "genre": "Fiction Novel",
    "language": "French",
    "country": "France",
    "ISBN": "",
    "Designer": "",
    "year": "1973",
    "pages": "137",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "The People of the Abyss",
    "subtitle": "",
    "author": "Jack London",
    "publisher": "SeaWolf Press",
    "collection": "",
    "genre": "Fiction",
    "language": "English",
    "country": "USA",
    "ISBN": "978-1948132596",
    "Designer": "",
    "year": "2018",
    "pages": "302",
    "width[mm]": "133.35",
    "height[mm]": "203.20"
  },
  {
    "title": "The Name of the Rose",
    "subtitle": "",
    "author": "Umberto Eco",
    "publisher": "Mariner Books",
    "collection": "",
    "genre": "Historical Novel, Mystery, Romance",
    "language": "English",
    "country": "Italy",
    "ISBN": "978-0544176560",
    "Designer": "",
    "year": "2014",
    "pages": "592",
    "width[mm]": "134.87",
    "height[mm]": "203.20"
  },
  {
    "title": "Things Fall Apart",
    "subtitle": "",
    "author": "Chinua Achebe",
    "publisher": "Penguin Books",
    "collection": "",
    "genre": "Romance",
    "language": "English",
    "country": "Nigéria",
    "ISBN": "978-0385474542",
    "Designer": "",
    "year": "1994",
    "pages": "209",
    "width[mm]": "132.08",
    "height[mm]": "203.20"
  },
  {
    "title": "Anna Karenina",
    "subtitle": "",
    "author": "Leo Tolstoy",
    "publisher": "Penguin",
    "collection": "",
    "genre": "Romance,Novel Fiction",
    "language": "English",
    "country": "Russia",
    "ISBN": "978-0393096712",
    "Designer": "",
    "year": "1877",
    "pages": "874",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Dubliners",
    "subtitle": "",
    "author": "James Joyce",
    "publisher": "Grant Richards ltd.",
    "collection": "",
    "genre": "Short Story",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "978-0679405740",
    "Designer": "",
    "year": "1914",
    "pages": "152",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Hunger",
    "subtitle": "",
    "author": "Knut Hamson",
    "publisher": "Penguin",
    "collection": "",
    "genre": "Romance, Psychological Novel",
    "language": "English",
    "country": "Norwegian",
    "ISBN": "978-0141180649",
    "Designer": "",
    "year": "1890",
    "pages": "272",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Memorial do Convento",
    "subtitle": "",
    "author": "José Saramago",
    "publisher": "Caminho",
    "collection": "",
    "genre": "Romance Histórico",
    "language": "Português",
    "country": "Portugal",
    "ISBN": "978-9720046710",
    "Designer": "",
    "year": "1982",
    "pages": "402",
    "width[mm]": "130.00",
    "height[mm]": "210.00"
  },
  {
    "title": "Casa de Bonecas ",
    "subtitle": "",
    "author": "Henrik Ibsen",
    "publisher": "Porto Editora",
    "collection": "",
    "genre": "Novel",
    "language": "Português",
    "country": "Norwegian",
    "ISBN": "978-3518189337",
    "Designer": "",
    "year": "1879",
    "pages": "",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Eugene Onegin",
    "subtitle": "",
    "author": "Aleksander Pushkin",
    "publisher": "Thomas Y. Crowell & Company",
    "collection": "",
    "genre": "Novel, Romance",
    "language": "English",
    "country": "Russia",
    "ISBN": "850-1084735",
    "Designer": "",
    "year": "1833",
    "pages": "288",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "La Storia",
    "subtitle": "",
    "author": "Elsa Morante",
    "publisher": "Penguin",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "Italy",
    "ISBN": "978-1586420048",
    "Designer": "",
    "year": "1977",
    "pages": "676",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Critique of Pure Reason",
    "subtitle": "",
    "author": "Immanuel Kant",
    "publisher": "Macmillan Company",
    "collection": "",
    "genre": "Philosophy",
    "language": "English",
    "country": "German",
    "ISBN": "978-9896230920",
    "Designer": "",
    "year": "1922",
    "pages": "254",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Pride and Prejudice",
    "subtitle": "",
    "author": "Jane Austen",
    "publisher": "Penguin",
    "collection": "",
    "genre": "Novel",
    "language": "English",
    "country": "United Kingdom",
    "ISBN": "978-0140434262",
    "Designer": "",
    "year": "1813",
    "pages": "278",
    "width[mm]": "",
    "height[mm]": ""
  },
  {
    "title": "Uma Solidão Demasiado Ruidosa",
    "subtitle": "",
    "author": "Bohumil Hrabal",
    "publisher": "Harcourt",
    "collection": "",
    "genre": "Novel",
    "language": "Português",
    "country": "Tchecoslovaquia",
    "ISBN": "853-5916350",
    "Designer": "",
    "year": "1976",
    "pages": "106",
    "width[mm]": "",
    "height[mm]": ""
  }
]